stages:
  - build
  - test
  - deploy

# Job build
build_job:
  stage: build
  script:
    - echo "Building the project..."

# Job test
test_job:
  stage: test
  script:
    - echo "Running tests..."

# Job deploy
deploy_job:
  stage: deploy
  script:
    - ssh ubuntu@52.64.135.244 "cd /var/www/html/ecm01 && git pull origin develop"
  only:
    - develop